### ISSUE TITLE
Turgenev Windows rev32 by Jim Ablett including a logo

### ISSUE THREAD

**Issue by ChessGUI** [dahc/turgenev#4]
cf. attached file because your "Turgenev-Master"
[Turgenev Windows rev32 JA.zip](https://github.com/dahc/turgenev/files/753003/Turgenev.Windows.rev32.JA.zip)
 compilation has no Windows binary

**Comment by dahc** [comment]
I'm not sure what you're asking for... I've never released compiled binaries for this project. That's from an old forum post by a third party whom I have no control over.

**Comment by ChessGUI** [comment]
Jim Abett who has retired from computerchess in 2013, made a lot of Windows/Linux compiles of chess engines - the former download link https://dl.dropboxusercontent.com/u/5047625/turgenev-rev32-ja.exe > error 429: This account's links are generating too much traffic and have been temporarily disabled!

**Comment by dahc** [comment]
Thanks for the clarification, and also thanks for the logo! I didn't notice it the first time I looked at this.

I'm working on a rewrite against @malbrecht's chess library, and once that's more stable than the current version (soon, since the old code is so janky), I'll start putting up releases here on GitHub with more sensible version numbers, etc. I'm going to hold off on publishing any new builds until that rewrite is merged into master, though, so I'll go ahead and close this ticket.

Thanks again for your help! I might come pester you later for help with Windows builds; I'm mostly a Linux guy. :)
